from nome2 import *
A=("Nilo")
A=Nome("Nilo")
print(A == Nome("Nilo"))
print(A != Nome("Nilo"))
print(A > Nome("Nilo"))
print(A < Nome("Nilo"))
print(A <= Nome("Nilo"))
print(A >= Nome("Nilo"))
print(A.CriaChave("X"))
print(Nome.CriaChave("X"))